apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service
          image: nextordevs/browserchat-backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: backend-service
  ports:
    - name: backend-service-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: backend-service-https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-nodeport
spec:
  type: NodePort
  selector:
    app: backend-service
  ports:
    - name: backend-service-http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30102
    - name: backend-service-https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30202