apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
        - name: web-client
          image: nextordevs/browserchat-client
---
apiVersion: v1
kind: Service
metadata:
  name: web-client-clusterip
spec:
  type: ClusterIP
  selector:
    app: web-client
  ports:
    - name: web-client-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: web-client-https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: web-client-nodeport
spec:
  type: NodePort
  selector:
    app: web-client
  ports:
    - name: web-client-http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101
    - name: web-client-https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30201