apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bot-service
  template:
    metadata:
      labels:
        app: bot-service
    spec:
      containers:
        - name: bot-service
          image: nextordevs/browserchat-bot